# DEFAULT_FOLDER = crkbd/rev1
CONVERT_TO=elite_pi
OLED_ENABLE = yes
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes


# RGBLIGHT_DRIVER = sk6812
# RGB_MATRIX_DRIVER = ws2812



# PIN_COMPATIBLE = promicro

# PIN_COMPATIBLE = elite_c
# OLED_DRIVER = SSD1306
# I2C_DRIVER = I2CD1
# I2C1_SDA_PIN = GP2
# I2C1_SCL_PIN = GP3
# RGBLIGHT_DRIVER = sk6812
# RGB_MATRIX_DRIVER = ws2812
# RGB_MATRIX_CUSTOM_USER = yes
# To use custom effects in your code, simply prepend RGB_MATRIX_CUSTOM_ to the effect name specified in RGB_MATRIX_EFFECT().
